### ISSUE TITLE
Curve Fitting Algorithm in Processing

### ISSUE THREAD

**Issue by PAk-CatchFire** [PeteLaric/etherkeys#1]
Hello, I would like to ask you if you are able to share your curve fitting algorithm for processing.org. 
I found your video on youtube, but it is unreadable.

Thank you mate.

**Comment by PeteLaric** [comment]
Hi!  Thanks for reaching out.  I assume you are the same person who commented on YouTube earlier?

I looked for the code but unfortunately, it is nowhere to be found.  I filmed that video over nine years ago... shortly before I returned to school for engineering.  I now know much higher maths and would approach the problem differently if I had it to do over again.

I can't remember exactly what approach I used in the video, but I would guess that it was some variant of either gradient descent (using numerical gradients), or simulated annealing.  It clearly isn't optimal and probably wouldn't do a very good job of finding coefficients that are very large or very small.  For problems of this nature, I recommend MATLAB (the open source version is Octave).  Using the built-in functions polyfit and polyval, you can solve massive polynomials with dozens of coefficients, instantaneously.  It is also very easy to plot the result, and animations can easily be made by looping a routine that repaints the same figure.

If you really want the code in the video, you could probably just copy it off the screen.  Hope this is helpful to you!  Cheers, ~Pete
